const express = require('express')
const path = require('path')
const app = express()
const fs = require('fs')
const workboxBuild = require('workbox-build')
const showdown  = require('showdown')

// Docs is used by pages as an option instead of root
app.use(express.static('docs'))

const buildSW = () => {
  // This will return a Promise
  console.log('building SW')
  return workboxBuild.generateSW({
    globDirectory: 'docs',
    globPatterns: [
      '**/*.{png,jpg,webp,js,ico,html,txt,webmanifest,xml,css}',
    ],
    swDest: 'docs/sw.js', 
  })
}

// Simple route set up for page editing
app.get('/', (req, res) => {
    res.sendFile(path.join(__dirname + '/docs/index.html'))
})

// Defaults to pulling markdown data from the README.md file in the root of the git repo
fs.readFile('./README.md', (err, data) => {
  let converter = new showdown.Converter(),
    text = data.toString(),
    html = converter.makeHtml(text)
  console.log(html.toString())
  // Do something with the HTML generated by Showdown.
  // Call buildSW last so all assets are versioned correctly
  buildSW()
})


app.listen(3000) 